### ISSUE TITLE
AIP references not showing

### ISSUE THREAD

**Issue by csgrant00** [adsabs/adsabs-pyingest#126]
calling ref_handler with     ref_handler.writeref(d,'aip')
still results in to references files being written to /proj/ads/references/  directory,
e.g. /proj/ads/abstracts/data/AIP/JATS.0127/JCP/v154/i2/024904_1/Markup/VOR_10.1063_5.0033645.xml

**Comment by seasidesparrow** [comment]
There's no AIP refhandler yet.  I'll start working on one.
