### ISSUE TITLE
small caps <sc> not being rendered in classic serializer

### ISSUE THREAD

**Issue by csgrant00** [adsabs/adsabs-pyingest#132]
<sc>ii</sc> should be rendered as "II"

**Comment by seasidesparrow** [comment]
@csgrant00 do you have an example data file?

**Comment by csgrant00** [comment]
/proj/ads/abstracts/data/MNRAS/503.1/TagTextFiles:

stab340.xml
staa3773.xml
staa645.xml
stab566.xml
stab518.xml
stab517.xml
stab513.xml

**Comment by seasidesparrow** [comment]
This is fixed in the jats.py parser, see https://github.com/adsabs/adsabs-pyingest/blob/e872effd59484d0cfee3ce50dd2c9adab4adc8e7/pyingest/parsers/jats.py#L58.  If there are any other data delivery formats that use the "sc" html tag, let me know.
