### ISSUE TITLE
Upgrade of xmltodict, namespace support

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsabs-pyingest#14]
We are using an early version of xmltodict (bundled into this repo) to parse XML documents.  The current version of the package supports some additional features such as XML namespaces and predictable handling of element arrays in XML documents, so we should at some point upgrade and update the code to do real namespace validation and processing.

**Comment by seasidesparrow** [comment]
I forked the current xmltodict (0.11.0) and diffed it with what we're using (0.9.2).  I'm not seeing any huge differences.  Maybe half a day to switch and test it?

**Comment by aaccomazzi** [comment]
Sounds good to me!  We should also consider whether it makes sense for us to have our own copy or whether we just put it in requirements.txt

**Comment by seasidesparrow** [comment]
I think the latter -- it's easier to maintain.
