### ISSUE TITLE
JCAP affiliation parsing spotty

### ISSUE THREAD

**Issue by csgrant00** [adsabs/adsabs-pyingest#142]
Many affiliations being skipped for JCAP:

/proj/ads/articles/sources/STACKS/1475-7516/2021/04/002/jcap_2021_04_002.xml
/proj/ads/articles/sources/STACKS/1475-7516/2021/04/003/jcap_2021_04_003.xml
/proj/ads/articles/sources/STACKS/1475-7516/2021/04/005/jcap_2021_04_005.xml
/proj/ads/articles/sources/STACKS/1475-7516/2021/04/014/jcap_2021_04_014.xml
/proj/ads/articles/sources/STACKS/1475-7516/2021/04/021/jcap_2021_04_021.xml
/proj/ads/articles/sources/STACKS/1475-7516/2021/04/023/jcap_2021_04_023.xml

etc.

**Comment by seasidesparrow** [comment]
JCAP is IOP?

**Comment by csgrant00** [comment]
YEs

*************************************************************************

 Carolyn Stern Grant              Astrophysics Data System (ADS)

 ***@***.***        Center for Astrophysics

 617-495-7154 (voicemail)      60 Garden Street  MS 83

 617-495-7356 fax                 Cambridge, MA  02138

*************************************************************************

**Comment by seasidesparrow** [comment]
This will be fixed in the next release.
