### ISSUE TITLE
Volume - Page - ID fix for PASP

### ISSUE THREAD

**Issue by seasidesparrow** [adsabs/adsabs-pyingest#153]
The leading two digits of the id number need to be converted to a lower-case letter.

**Comment by seasidesparrow** [comment]
@csgrant00 Can you verify whether this issue was fixed by https://github.com/adsabs/adsabs-pyingest/pull/156 ?

**Comment by csgrant00** [comment]
Yes, it is working.

*************************************************************************

 Carolyn Stern Grant              Astrophysics Data System (ADS)

 ***@***.***        Center for Astrophysics

 617-495-7154 (voicemail)      60 Garden Street  MS 83

 617-495-7356 fax                 Cambridge, MA  02138

*************************************************************************
