### ISSUE TITLE
ArXiv parser isn't handling last names as classic does (for multi-name authors, esp. Spanish)

### ISSUE THREAD

**Issue by seasidesparrow** [adsabs/adsabs-pyingest#29]
The result is that some arxiv papers are receiving two bibcodes, one of which comes from DI, the other from Classic, and the DI is both wrong *and* protected against deletion.  arxiv parser needs to use the same name flipping algorithm that Classic does.

**Comment by aaccomazzi** [comment]
Example: arXiv:1812.07474

**Comment by aaccomazzi** [comment]
We should probably base this off of https://nameparser.readthedocs.io/en/latest/ with our own knowledge base, found in `/proj/ads/abstracts/config/Authors/`

**Comment by seasidesparrow** [comment]
Importing text from issue #367:

This feature will be used for all future direct ingest pipelines, including those already running as of Feb 2019 (Arxiv, Asclepias?)

Background email: (Alberto to MT/curators, 2018 Aug 27:)

Accomazzi, Alberto aaccomazzi@cfa.harvard.edu
Mon, Aug 27, 2018, 12:29 PM
to Carolyn, Donna, me
Hi Matt,

The code that is responsible for author name parsing is here:
/proj/ads/soft/src/ads/perl/ADS/Abstracts/ADS-Abstracts-ArXiv/ArXiv.pm
specifically in fuction dc2ref you will find the author parser applying its rewriting logic, which in turn
is found here:
/proj/ads/soft/src/ads/perl/ADS/Authors/ADS-Authors-Names/

Checking the scant documentation in the code I see this at the beginning of the file:

# the author parser is used to reformat names that they treat differently
# from us. For example, consider the author name "Sidney van den Bergh";
# ADS formats it as "van den Bergh, Sidney" (the anglo way), while ArXiv
# formats is as " Bergh, Sidney van den" (the dutch way)

So even if we kill most of the reparsing we'd still want to worry about these edge cases.
....

**Comment by seasidesparrow** [comment]
The arXiv name parser relies on the subs parse_lastlast and parse_nosep_lastlast from ADS::Authors::Names::Parser.pm, which are:
```
sub parse_lastlast {
    my $self = shift or return undef;
    my $a = shift or return undef;
    my $flsep = $self->{flsep};

    my @tmp = split(/\Q$flsep\E\s*/,$a);
    my $last = pop(@tmp);
    $tmp[0] = $self->add_first_dots($tmp[0]) if ($self->{first_nodots});
    my $first = join(", ",@tmp);

    pdebug("$module: parse_lastlast: parsing name: \"$a\"; ",
           "separator = \"$flsep\"\n",
           "$module: last = \"$last\"; first = \"$first\"");

    $self->swapchinese($first,$last);

    return ($first,$last);
}```

```
sub parse_nosep_lastlast {
    my $self = shift or return undef;
    my $a = shift or return undef;

    # cleanup name first in case there is a period at the end
    # of the last name
    # $a =~ s/^\s+|\s*\.?\s*$//g;
    $a =~ s/^\s+|\s*$//g;
    pdebug($module, "::parse_nosep_lastlast: parsing: >$a<");

    my $last = "";
    my $first = "";
    $last = $1  if ($a =~ s/\s*([^\s\.]+\.?)$//);
    $first = $1 if ($a =~ s/^(\S+)\s*//);
    $first = $self->add_first_dots($first) if ($self->{first_nodots});

    pdebug($module, "::parse_nosep_lastlast: initial parse: ",
           "first = \"$first\"; last = \"$last\"");

    my $middle = "";
    while ($a =~ s/\s*(\S+)\s*$//) {
        my $name = $1;
        if ($self->islast($name)) {
            # double last name
            pwarn("found double last name: \"$name\"");
            $last = "$name $last";
        } elsif ($self->isfirst($name)) {
            # middle name
            pwarn("found middle name: \"$name\"");
            $middle = $name;
            last;
        } elsif ($name =~ /^\-?\w?\w\.?$/) {
            # middle name looks like one of these: A, A., -A, -A., Ch.
            $middle = $name;
            last;
        } elsif ($name =~ /^(\-?\w\.)+$/) {
            # middle name looks like one of these: A.B.
            $middle = $name;
            last;
        } elsif ($self->{'defname'} eq 'last') {
            # default to last
            pwarn("defaulted to last name: \"$name\"");
            $last = "$name $last";
        } else {
            # default to middle
            pwarn("defaulted to middle name: \"$name\"");
            $middle = $name;
            last;
        }
    }
    $middle = "$a $middle" if ($a);
    $middle =~ s/^\s+|\s+$//g;
    pdebug("$module: middle name = \"$middle\"") if ($middle);

    $first .= " $middle" if ($middle);
    $self->swapchinese($first,$last);

    return ($first,$last);
}```
