### ISSUE TITLE
better handling of footnotes

### ISSUE THREAD

**Issue by csgrant00** [adsabs/adsabs-pyingest#69]
Footnotes are often in title, and in the past, we have removed them from the title and appended them as a new paragraph of the abstracts.

example 2020AJ....159..186D
/proj/ads/articles/sources/STACKS/1538-3881/159/5/186/aj_159_5_186.refs.xml

**Comment by seasidesparrow** [comment]
See 'article-title' ...1538-3881/159/5/186/aj_159_5_186.xml

**Comment by seasidesparrow** [comment]
Will be fixed when I merge https://github.com/seasidesparrow/adsabs-pyingest/commit/160407fe7447cea857ca5cecad903a72c5fc5e3b
