### ISSUE TITLE
improve handling UAT keywords

### ISSUE THREAD

**Issue by csgrant00** [adsabs/adsabs-pyingest#89]
Modify handling of IOP keywords as follows:

1. For kwd-group containing UAT keywords
<kwd-group kwd-group-type="author">
<title content-type="vocab">unified-astronomy-thesaurus</title>
<compound-kwd>
<compound-kwd-part content-type="vocab-term-identifier">http://astrothesaurus.org/uat/14</compound-kwd-part>

extract the uat number and tag in %U:

%U 14, 17, etc.

2. For kwd-group containing AAS keywords:
<kwd-group kwd-group-type="AAS">
<kwd>Accretion</kwd>

extract the keyword concept, do not convert to UAT and tag in %K

%K Accretion, etc.

This should fix the introduction of UAT terms into OUP data.

During loading, I will interpret %U -> "UAT Keywords" and %K -> "Astronomy Keywords" (in genassign.pl)

See /proj/ads/articles/sources/STACKS/0004-637X/896/2/146/apj_896_2_146.xml
for a record containing both kwd-groups

**Comment by seasidesparrow** [comment]
My current revision of jats.py splits the existing keywords field from the UAT by creating output_metadata['uatkeys'] ('uatkeys' has also been added to the serializer).  I now need to add code to grab cases where the UAT is presented as outlined above, hopefully before COB on 7/20/20

**Comment by seasidesparrow** [comment]
Feature added in #90
