### ISSUE TITLE
jats.py needs to extract numpages

### ISSUE THREAD

**Issue by csgrant00** [adsabs/adsabs-pyingest#94]
%J field should read, e.g.

The Astrophysical Journal, Vol. 898, id. 1 <NUMPAGES>18</NUMPAGES> pp.

**Comment by seasidesparrow** [comment]
@csgrant00 is this format correct?  No punctuation between "id.76" and "15 pp."?

%J The Astronomical Journal, Volume 159, Issue 2, id.76 15 pp.

**Comment by csgrant00** [comment]
I agree a comma would be better.
